version: '3.7'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql-server
    container_name: my-mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: capstone
    networks:
      - linkednetwork

  adminer:
    image: adminer
    container_name: my-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - linkednetwork

  client:
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: capstone
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_bWFpbi1saW9uZXNzLTI4LmNsZXJrLmFjY291bnRzLmRldiQ
      CLERK_SECRET_KEY: sk_test_QgCg0luX1db1rUyOYH4YwA1a9Sj6thlwLLpxyFpd7g
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-server
    container_name: my-client-server
    command: npm run dev
    volumes:
      # bind mounting entire project folder to container for watcher detection
      - ./client:/usr/app/client
      # node_modules gets its own volume for all containers to share
      - node_modules_client:/usr/app/client/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - linkednetwork

volumes:
  node_modules_client:
  data-volume:


networks:
  linkednetwork:
